import { Tactic } from './types';

export const MARKETING_TACTICS: Tactic[] = [
  // SEO Tactics
  {
    id: 'technical-seo',
    name: 'Technical SEO Optimization',
    category: 'seo',
    baseCost: 5000,
    teamHours: 40,
    baseROI: 1.8,
    compounding: true,
    industryMultipliers: { healthcare: 1.4, legal: 1.3, ecommerce: 1.2, saas: 1.3, manufacturing: 0.9 },
    sizeMultipliers: { startup: 1.2, smb: 1.1, enterprise: 0.9 },
    description: 'Site speed, mobile optimization, schema markup. Compounds 15% per quarter.',
    isRecurring: true,
  },
  {
    id: 'content-seo',
    name: 'Content-Driven SEO',
    category: 'seo',
    baseCost: 8000,
    teamHours: 60,
    baseROI: 2.2,
    compounding: true,
    industryMultipliers: { healthcare: 1.5, legal: 1.6, ecommerce: 1.0, saas: 1.5, manufacturing: 1.2 },
    sizeMultipliers: { startup: 1.3, smb: 1.1, enterprise: 0.9 },
    description: 'High-quality content targeting long-tail keywords. Compounds 18% per quarter.',
    isRecurring: true,
  },
  {
    id: 'local-seo',
    name: 'Local SEO & GMB Optimization',
    category: 'seo',
    baseCost: 3000,
    teamHours: 25,
    baseROI: 1.6,
    compounding: false,
    industryMultipliers: { healthcare: 1.8, legal: 1.5, ecommerce: 0.6, saas: 0.7, manufacturing: 1.1 },
    sizeMultipliers: { startup: 1.4, smb: 1.3, enterprise: 0.7 },
    description: 'Google My Business, local citations, review generation.',
    isRecurring: false,
  },
  
  // Paid Ads Tactics
  {
    id: 'google-search-ads',
    name: 'Google Search Ads',
    category: 'paid-ads',
    baseCost: 15000,
    teamHours: 30,
    baseROI: 1.4,
    compounding: false,
    industryMultipliers: { healthcare: 1.2, legal: 0.9, ecommerce: 1.8, saas: 1.4, manufacturing: 0.7 },
    sizeMultipliers: { startup: 0.8, smb: 1.0, enterprise: 1.3 },
    description: 'High-intent search ads. Saturates after Q2 (diminishing returns).',
    isRecurring: false,
  },
  {
    id: 'facebook-ads',
    name: 'Facebook & Instagram Ads',
    category: 'paid-ads',
    baseCost: 12000,
    teamHours: 25,
    baseROI: 1.3,
    compounding: false,
    industryMultipliers: { healthcare: 0.8, legal: 0.6, ecommerce: 1.9, saas: 1.2, manufacturing: 0.6 },
    sizeMultipliers: { startup: 1.1, smb: 1.1, enterprise: 1.0 },
    description: 'Targeting, retargeting, lookalike audiences. Saturates after Q3.',
    isRecurring: false,
  },
  {
    id: 'linkedin-ads',
    name: 'LinkedIn Sponsored Content',
    category: 'paid-ads',
    baseCost: 10000,
    teamHours: 20,
    baseROI: 1.1,
    compounding: false,
    industryMultipliers: { healthcare: 1.1, legal: 1.4, ecommerce: 0.6, saas: 1.6, manufacturing: 1.3 },
    sizeMultipliers: { startup: 0.9, smb: 1.0, enterprise: 1.4 },
    description: 'B2B targeting, thought leadership ads. High CPM but quality leads.',
    isRecurring: false,
  },
  
  // Content Marketing
  {
    id: 'blogging',
    name: 'Strategic Blogging',
    category: 'content',
    baseCost: 6000,
    teamHours: 50,
    baseROI: 1.9,
    compounding: true,
    industryMultipliers: { healthcare: 1.5, legal: 1.6, ecommerce: 1.0, saas: 1.5, manufacturing: 1.2 },
    sizeMultipliers: { startup: 1.3, smb: 1.1, enterprise: 0.9 },
    description: 'Educational content, thought leadership. Compounds 12% per quarter.',
    isRecurring: true,
  },
  {
    id: 'video-content',
    name: 'Video Marketing',
    category: 'content',
    baseCost: 9000,
    teamHours: 45,
    baseROI: 1.7,
    compounding: true,
    industryMultipliers: { healthcare: 1.4, legal: 1.1, ecommerce: 1.6, saas: 1.5, manufacturing: 1.3 },
    sizeMultipliers: { startup: 1.2, smb: 1.1, enterprise: 1.0 },
    description: 'YouTube, product demos, testimonials. Compounds 10% per quarter.',
    isRecurring: true,
  },
  {
    id: 'case-studies',
    name: 'Case Studies & Whitepapers',
    category: 'content',
    baseCost: 7000,
    teamHours: 55,
    baseROI: 1.5,
    compounding: false,
    industryMultipliers: { healthcare: 1.3, legal: 1.5, ecommerce: 0.8, saas: 1.6, manufacturing: 1.7 },
    sizeMultipliers: { startup: 0.9, smb: 1.0, enterprise: 1.4 },
    description: 'In-depth client success stories. High value for B2B.',
    isRecurring: false,
  },
  
  // Social Media
  {
    id: 'organic-social',
    name: 'Organic Social Media',
    category: 'social',
    baseCost: 4000,
    teamHours: 40,
    baseROI: 1.2,
    compounding: true,
    industryMultipliers: { healthcare: 0.9, legal: 0.8, ecommerce: 1.5, saas: 1.3, manufacturing: 0.7 },
    sizeMultipliers: { startup: 1.4, smb: 1.2, enterprise: 0.8 },
    description: 'Community building, engagement. Compounds 8% per quarter.',
    isRecurring: true,
  },
  {
    id: 'influencer-marketing',
    name: 'Influencer Partnerships',
    category: 'social',
    baseCost: 14000,
    teamHours: 30,
    baseROI: 1.6,
    compounding: false,
    industryMultipliers: { healthcare: 1.1, legal: 0.7, ecommerce: 2.0, saas: 1.2, manufacturing: 0.6 },
    sizeMultipliers: { startup: 1.1, smb: 1.0, enterprise: 0.9 },
    description: 'Micro/macro influencer collaborations. High reach, variable quality.',
    isRecurring: false,
  },
  
  // Events
  {
    id: 'webinars',
    name: 'Webinar Series',
    category: 'events',
    baseCost: 5000,
    teamHours: 35,
    baseROI: 1.4,
    compounding: false,
    industryMultipliers: { healthcare: 1.3, legal: 1.4, ecommerce: 0.9, saas: 1.7, manufacturing: 1.2 },
    sizeMultipliers: { startup: 1.2, smb: 1.1, enterprise: 1.2 },
    description: 'Educational webinars, product demos. Lead generation.',
    isRecurring: false,
  },
  {
    id: 'trade-shows',
    name: 'Industry Trade Shows',
    category: 'events',
    baseCost: 18000,
    teamHours: 60,
    baseROI: 1.3,
    compounding: false,
    industryMultipliers: { healthcare: 1.2, legal: 1.5, ecommerce: 0.5, saas: 1.1, manufacturing: 2.0 },
    sizeMultipliers: { startup: 0.7, smb: 1.0, enterprise: 1.5 },
    description: 'Booth, networking, brand visibility. Essential for manufacturing.',
    isRecurring: false,
  },
  {
    id: 'local-events',
    name: 'Local Community Events',
    category: 'events',
    baseCost: 3500,
    teamHours: 25,
    baseROI: 1.1,
    compounding: false,
    industryMultipliers: { healthcare: 1.6, legal: 1.3, ecommerce: 0.6, saas: 0.8, manufacturing: 1.0 },
    sizeMultipliers: { startup: 1.3, smb: 1.2, enterprise: 0.7 },
    description: 'Sponsorships, community engagement. Great for local businesses.',
    isRecurring: false,
  },
  
  // PR & Media
  {
    id: 'pr-campaign',
    name: 'PR & Media Outreach',
    category: 'pr',
    baseCost: 10000,
    teamHours: 50,
    baseROI: 1.5,
    compounding: false,
    industryMultipliers: { healthcare: 1.3, legal: 1.4, ecommerce: 0.9, saas: 1.2, manufacturing: 1.1 },
    sizeMultipliers: { startup: 1.2, smb: 1.0, enterprise: 1.3 },
    description: 'Press releases, media coverage, thought leadership.',
    isRecurring: false,
  },
  {
    id: 'podcast-sponsorship',
    name: 'Podcast Sponsorships',
    category: 'pr',
    baseCost: 6000,
    teamHours: 15,
    baseROI: 1.3,
    compounding: false,
    industryMultipliers: { healthcare: 1.2, legal: 1.1, ecommerce: 1.4, saas: 1.5, manufacturing: 0.9 },
    sizeMultipliers: { startup: 1.1, smb: 1.0, enterprise: 1.0 },
    description: 'Targeted podcast ads. Niche audience engagement.',
    isRecurring: false,
  },
  
  // Email Marketing
  {
    id: 'email-nurture',
    name: 'Email Nurture Campaigns',
    category: 'email',
    baseCost: 4500,
    teamHours: 30,
    baseROI: 1.8,
    compounding: true,
    industryMultipliers: { healthcare: 1.3, legal: 1.2, ecommerce: 1.6, saas: 1.5, manufacturing: 1.1 },
    sizeMultipliers: { startup: 1.2, smb: 1.1, enterprise: 1.0 },
    description: 'Automated drip campaigns. Compounds 10% per quarter with list growth.',
    isRecurring: true,
  },
  {
    id: 'newsletter',
    name: 'Monthly Newsletter',
    category: 'email',
    baseCost: 3000,
    teamHours: 20,
    baseROI: 1.4,
    compounding: true,
    industryMultipliers: { healthcare: 1.2, legal: 1.1, ecommerce: 1.3, saas: 1.4, manufacturing: 1.0 },
    sizeMultipliers: { startup: 1.3, smb: 1.1, enterprise: 0.9 },
    description: 'Regular audience engagement. Builds brand loyalty over time.',
    isRecurring: true,
  },
  
  // Partnerships
  {
    id: 'referral-program',
    name: 'Referral Partner Program',
    category: 'partnerships',
    baseCost: 7000,
    teamHours: 40,
    baseROI: 2.0,
    compounding: true,
    industryMultipliers: { healthcare: 1.8, legal: 2.0, ecommerce: 1.2, saas: 1.4, manufacturing: 1.6 },
    sizeMultipliers: { startup: 1.1, smb: 1.2, enterprise: 1.3 },
    description: 'Partner ecosystem development. Compounds 14% per quarter.',
    isRecurring: true,
  },
  {
    id: 'strategic-alliances',
    name: 'Strategic Business Alliances',
    category: 'partnerships',
    baseCost: 12000,
    teamHours: 50,
    baseROI: 1.7,
    compounding: false,
    industryMultipliers: { healthcare: 1.4, legal: 1.6, ecommerce: 1.1, saas: 1.3, manufacturing: 1.8 },
    sizeMultipliers: { startup: 0.9, smb: 1.1, enterprise: 1.5 },
    description: 'Co-marketing, joint ventures. High value but relationship-dependent.',
    isRecurring: false,
  },
];

export const getTacticById = (id: string): Tactic | undefined => {
  return MARKETING_TACTICS.find(t => t.id === id);
};

export const getTacticsByCategory = (category: string): Tactic[] => {
  return MARKETING_TACTICS.filter(t => t.category === category);
};
