import React from "react";
import OptimizedImage from "@components/media/OptimizedImage";

// Import manifest - will be generated by build script
// Handle missing manifest gracefully in development
let manifest: Record<string, unknown> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const manifestData = require("@data/images.manifest.json");
  manifest = manifestData || {};
} catch {
  // Manifest doesn't exist yet, use empty object
  manifest = {};
}

const picks = Object.keys(manifest || {}).slice(0, 14);

export default function FromTheWork() {
  if (!manifest || picks.length === 0) {
    return null;
  }

  return (
    <section className="mx-auto max-w-7xl px-4 py-12">
      <h3 className="mb-6 text-lg font-semibold text-neutral-200">From the Work</h3>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-7">
        {picks.map((f) => (
          <OptimizedImage
            key={f}
            src={f}
            alt={f.replace(/\.(jpe?g|png)$/i, '')}
            className="rounded-xl ring-1 ring-white/5"
          />
        ))}
      </div>
    </section>
  );
}

