export interface PhotoItem {
  src: string;
  width: number; // Placeholder dimensions until real metadata is available
  height: number;
  alt: string;
  key: string;
}

/**
 * Load the photography manifest generated by `npm run sync`.
 * Returns an array of photo objects ready for the masonry gallery.
 */
export const loadPhotography = async (): Promise<PhotoItem[]> => {
  try {
    const response = await fetch('/images/photography/manifest.json');
    if (!response.ok) {
      throw new Error('Manifest not found');
    }

    const filenames = (await response.json()) as unknown;
    if (!Array.isArray(filenames)) {
      throw new Error('Invalid manifest format');
    }

    return filenames.map((file: string, index: number) => ({
      src: `/images/photography/${file}`,
      width: 400,
      height: index % 3 === 0 ? 600 : 400,
      alt: `Photography Portfolio ${index + 1}`,
      key: file,
    }));
  } catch (error) {
    console.warn('Failed to load photography manifest:', error);
    return [];
  }
};
