import React from "react";

// Type definition for manifest entry
interface ImageManifestEntry {
  width: number;
  height: number;
  base: string;
  color: string;
  blurDataURL: string;
}

// Import manifest - will be generated by build script
// Empty fallback file exists to prevent build failures
import manifestData from "@data/images.manifest.json";

const manifest = (manifestData || {}) as Record<string, ImageManifestEntry>;

type OptimizedImageProps = {
  src: string;
  alt: string;
  className?: string;
  priority?: boolean;
};

export default function OptimizedImage({ src, alt, className, priority }: OptimizedImageProps) {
  const m = manifest[src];

  if (!m) {
    // Fallback to regular img if not in manifest
    return (
      <img
        src={`/${src}`}
        alt={alt}
        className={className}
        loading={priority ? "eager" : "lazy"}
      />
    );
  }

  const { width, height, base, blurDataURL, color } = m;
  const ratio = (height / width) * 100;

  return (
    <div
      className={`relative overflow-hidden ${className ?? ""}`}
      style={{ backgroundColor: color }}
    >
      <div style={{ paddingTop: `${ratio}%` }} />
      <img
        src={`/${base}.webp`}
        srcSet={`/${base}.avif 1x, /${base}.webp 1x`}
        alt={alt}
        loading={priority ? "eager" : "lazy"}
        decoding="async"
        className="absolute inset-0 h-full w-full object-cover"
        style={{
          backgroundImage: `url(${blurDataURL})`,
          backgroundSize: "cover",
          filter: "blur(0px)"
        }}
      />
    </div>
  );
}

