// Export all icons from a single location for easy importing
export {
  IconBrain,
  IconDiamond,
  IconBook,
  IconChart,
  IconBuilding,
  IconRefresh,
  IconTarget,
  IconRocket,
  IconAlert,
  IconLightbulb,
  IconPalette,
  IconUsers,
  IconGraduationCap,
  IconBriefcase,
  IconMail,
  IconCode,
  IconSoccer,
  IconTool,
  IconTrendingUp,
  IconMap,
  IconRobot,
  IconStar,
  IconPackage,
  IconDollar,
  IconSearch,
  IconCreditCard,
  IconClipboard,
  IconHospital,
  type IconProps,
} from './Icon';

// Icon mapping for easy lookup
export const iconMap = {
  brain: 'IconBrain',
  diamond: 'IconDiamond',
  book: 'IconBook',
  chart: 'IconChart',
  building: 'IconBuilding',
  refresh: 'IconRefresh',
  target: 'IconTarget',
  rocket: 'IconRocket',
  alert: 'IconAlert',
  lightbulb: 'IconLightbulb',
  palette: 'IconPalette',
  users: 'IconUsers',
  graduation: 'IconGraduationCap',
  briefcase: 'IconBriefcase',
  mail: 'IconMail',
  code: 'IconCode',
  soccer: 'IconSoccer',
  tool: 'IconTool',
  trendingUp: 'IconTrendingUp',
  map: 'IconMap',
  robot: 'IconRobot',
  star: 'IconStar',
  package: 'IconPackage',
  dollar: 'IconDollar',
  search: 'IconSearch',
  creditCard: 'IconCreditCard',
  clipboard: 'IconClipboard',
  hospital: 'IconHospital',
};

// Emoji to Icon mapping for migration
export const emojiToIconMap: Record<string, string> = {
  '🧠': 'IconBrain',
  '💎': 'IconDiamond',
  '📚': 'IconBook',
  '📊': 'IconChart',
  '📈': 'IconTrendingUp',
  '🏗️': 'IconBuilding',
  '🏛️': 'IconBuilding',
  '🔄': 'IconRefresh',
  '🎯': 'IconTarget',
  '🚀': 'IconRocket',
  '⚠️': 'IconAlert',
  '💡': 'IconLightbulb',
  '🎨': 'IconPalette',
  '👥': 'IconUsers',
  '🎓': 'IconGraduationCap',
  '💼': 'IconBriefcase',
  '✉️': 'IconMail',
  '💻': 'IconCode',
  '⚽': 'IconSoccer',
  '🔧': 'IconTool',
  '🗺️': 'IconMap',
  '🤖': 'IconRobot',
  '⭐': 'IconStar',
  '📦': 'IconPackage',
  '💰': 'IconDollar',
  '🔍': 'IconSearch',
  '💳': 'IconCreditCard',
  '📋': 'IconClipboard',
  '📑': 'IconClipboard',
  '🏥': 'IconHospital',
};
